#!/usr/bin/env bash

# Install nginx server
apt update && apt -y install nginx

# Create a simple index.html file
echo "Hello World!" > /var/www/html/index.html

# Start Nginx service
service nginx restart
