#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt update;
sudo apt -y install nginx;

echo "Hello World!" |sudo tee /var/www/html/index.html;

test="server_name _;\n\t/rewrite 301 ^\/redirect_me https:\/\/www.olukorede.tech;"

sudo sed -i "s/server_name _;/$test/" /etc/nginx/sites-enabled/default;

sudo service nginx restart
