#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt update
sudo apt -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html;

test="server_name _;\n\t/rewrite ^\/redirect_me https:\/\/www.google.com permanent;"

sudo sed -i "s|server_name _;|$test|" /etc/nginx/sites-available/default

sudo service nginx restart
